# Generated by Django 4.1.1 on 2022-10-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projektas',
            options={'ordering': ['pavadinimas']},
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='suma',
            field=models.FloatField(blank=True, null=True, verbose_name='Suma'),
        ),
    ]
