# Generated by Django 4.1.1 on 2022-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0002_alter_projektas_options_alter_saskaita_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Cover'),
        ),
    ]
