# Generated by Django 4.1.1 on 2022-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0003_projektas_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='darbas',
            name='busena',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Busena'),
        ),
        migrations.AlterField(
            model_name='darbas',
            name='pastabos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pastabos'),
        ),
    ]
