# Generated by Django 4.1.1 on 2022-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0004_darbas_busena_alter_darbas_pastabos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbas',
            name='busena',
            field=models.CharField(blank=True, choices=[('a', 'atlikta'), ('n', 'nepradeta'), ('p', 'pradeta')], max_length=100, null=True, verbose_name='Busena'),
        ),
    ]
