# Generated by Django 4.1.1 on 2022-10-25 06:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0005_alter_darbas_busena'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='aprasymas',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
